package com.NetherNoah.ParadiseMod.init.ModBlocks;

import com.NetherNoah.ParadiseMod.Utils;
import com.NetherNoah.ParadiseMod.CustomBlockCode.RubyPlateCode;
import com.NetherNoah.ParadiseMod.CustomBlockCode.buttonTicks.DiamondButtonTicks;
import com.NetherNoah.ParadiseMod.CustomBlockCode.buttonTicks.EmeraldButtonTicks;
import com.NetherNoah.ParadiseMod.CustomBlockCode.buttonTicks.IronButtonTicks;
import com.NetherNoah.ParadiseMod.CustomBlockCode.buttonTicks.QuickButton;
import com.NetherNoah.ParadiseMod.CustomBlockCode.pressurePlates.BedrockPlateCode;
import com.NetherNoah.ParadiseMod.CustomBlockCode.pressurePlates.DiamondPlateCode;
import com.NetherNoah.ParadiseMod.CustomBlockCode.pressurePlates.EmeraldPlateCode;
import com.NetherNoah.ParadiseMod.blocks.buttons.BedrockButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.CobblestoneButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.DiamondButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.DirtButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.EmeraldButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.EndButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.GlowingObsidianButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.GoldButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.GrassButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.IronButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.MossyButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.ObsidianButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.RubyButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.RustyButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.SilverButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.VoidButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.stoneVariants.AndesiteButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.stoneVariants.DioriteButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.stoneVariants.GraniteButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.wood.AcaciaButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.wood.BirchButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.wood.CactusButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.wood.DarkOakButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.wood.JungleButton;
import com.NetherNoah.ParadiseMod.blocks.buttons.wood.SpruceButton;
import com.NetherNoah.ParadiseMod.blocks.crystals.diamondCrystal;
import com.NetherNoah.ParadiseMod.blocks.crystals.emeraldCrystal;
import com.NetherNoah.ParadiseMod.blocks.crystals.quartzCrystal;
import com.NetherNoah.ParadiseMod.blocks.crystals.redstoneCrystal;
import com.NetherNoah.ParadiseMod.blocks.crystals.rubyCrystal;
import com.NetherNoah.ParadiseMod.blocks.misc.SaltLamp;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.BedrockPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.CobblestonePlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.DiamondPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.DirtPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.EmeraldPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.EndPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.GlowingObsidianPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.GrassPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.MossyPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.RubyPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.RustyPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.SilverPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.VoidPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.stoneVariants.AndesitePlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.stoneVariants.DioritePlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.stoneVariants.GranitePlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.wood.AcaciaPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.wood.BirchPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.wood.CactusPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.wood.DarkOakPlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.wood.JunglePlate;
import com.NetherNoah.ParadiseMod.blocks.pressurePlates.wood.SprucePlate;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.BlackRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.BlueRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.BrownRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.CyanRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.GrayRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.GreenRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.LightBlueRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.LimeRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.MagentaRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.OrangeRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.PinkRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.PurpleRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.RedRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.SilverRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.WhiteRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.YellowRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitBlackRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitBlueRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitBrownRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitCyanRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitGrayRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitGreenRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitLightBlueRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitLimeRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitMagentaRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitOrangeRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitPinkRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitPurpleRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitRedRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitSilverRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitWhiteRSLamp;
import com.NetherNoah.ParadiseMod.blocks.redstone.lamps.lit.LitYellowRSLamp;

import net.minecraft.block.Block;
import net.minecraft.block.BlockBush;
import net.minecraft.block.BlockButton;
import net.minecraft.block.BlockButtonStone;
import net.minecraft.block.BlockPressurePlate;
import net.minecraft.block.BlockRedstoneLight;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraftforge.fml.common.registry.ForgeRegistries;

public class Plates {
	
	//pressure plates
	public static BlockPressurePlate VoidPlate;
	public static BlockPressurePlate DirtPlate;
	public static BlockPressurePlate GrassPlate;
	public static BedrockPlateCode GlowingObsidianPlate;
	public static DiamondPlateCode DiamondPlate;
	public static EmeraldPlateCode EmeraldPlate;
	public static RubyPlateCode SilverPlate;
	public static RubyPlateCode RubyPlate;
	public static BedrockPlateCode BedrockPlate;
	public static BlockPressurePlate CactusPlate;
	public static BlockPressurePlate CobblestonePlate;
	public static BlockPressurePlate MossyPlate;
	public static BlockPressurePlate AcaciaPlate;
	public static BlockPressurePlate BirchPlate;
	public static BlockPressurePlate DarkOakPlate;
	public static BlockPressurePlate JunglePlate;
	public static BlockPressurePlate SprucePlate;
	public static BlockPressurePlate AndesitePlate;
	public static BlockPressurePlate DioritePlate;
	public static BlockPressurePlate GranitePlate;
	public static BlockPressurePlate EndPlate;
	public static BlockPressurePlate RustyPlate;

	public static void initAndRegister() {
		
		//pressure plates
		Utils.regBlock(VoidPlate=new VoidPlate());
		Utils.regBlock(DirtPlate=new DirtPlate());
		Utils.regBlock(GrassPlate=new GrassPlate());
		Utils.regBlock(CactusPlate=new CactusPlate());
		Utils.regBlock(EndPlate=new EndPlate());
		Utils.regBlock(GlowingObsidianPlate=new GlowingObsidianPlate());
		Utils.regBlock(DiamondPlate = new DiamondPlate());
		Utils.regBlock(EmeraldPlate = new EmeraldPlate());
		Utils.regBlock(SilverPlate = new SilverPlate());
		Utils.regBlock(RubyPlate = new RubyPlate());
		Utils.regBlock(BedrockPlate = new BedrockPlate());
		Utils.regBlock(MossyPlate = new MossyPlate());
		Utils.regBlock(CobblestonePlate = new CobblestonePlate());
		Utils.regBlock(AndesitePlate = new AndesitePlate());
		Utils.regBlock(DioritePlate = new DioritePlate());
		Utils.regBlock(GranitePlate = new GranitePlate());
		Utils.regBlock(AcaciaPlate = new AcaciaPlate());
		Utils.regBlock(BirchPlate = new BirchPlate());
		Utils.regBlock(DarkOakPlate = new DarkOakPlate());
		Utils.regBlock(JunglePlate = new JunglePlate());
		Utils.regBlock(SprucePlate = new SprucePlate());
		Utils.regBlock(RustyPlate=new RustyPlate());

	}
	public static void regRenders() {		
		Utils.regRender(VoidPlate);
		Utils.regRender(DirtPlate);
		Utils.regRender(GrassPlate);
		Utils.regRender(RustyPlate);
		Utils.regRender(CactusPlate);
		Utils.regRender(GlowingObsidianPlate);
		Utils.regRender(EndPlate);
		Utils.regRender(SilverPlate);
		Utils.regRender(DiamondPlate);
		Utils.regRender(EmeraldPlate);
		Utils.regRender(RubyPlate);
		Utils.regRender(BedrockPlate);
		Utils.regRender(MossyPlate);
		Utils.regRender(CobblestonePlate);
		Utils.regRender(AndesitePlate);
		Utils.regRender(DioritePlate);
		Utils.regRender(GranitePlate);
		Utils.regRender(AcaciaPlate);
		Utils.regRender(BirchPlate);
		Utils.regRender(DarkOakPlate);
		Utils.regRender(JunglePlate);
		Utils.regRender(SprucePlate);
	}
}
